// src/Keyword.js

module.exports = {
    CONST: "const",
    LEFT: "let",
    VAR: "var",
    FUNCTION: "function",
    IF: "if",
    ELSE: "else",
    FOR: "for",
    WHILE: "while",
    RETURN: "return",
    NEW: "new",
    CLASS: "class",
    IMPORT: "import",
    EXPORT: "export",
    DEFAULT: "default",
    FROM: "from",
    AS: "as",
    TRY: "try",
    CATCH: "catch",
    THROW: "throw",
    AWAIT: "await",
    ASYNC: "async",
    SWITCH: "switch",
    CASE: "case",
    BREAK: "break",
    CONTINUE: "continue",
    DO: "do",
    IN: "in",
    OF: "of",
};
